{"name":"Test01 -Verify Header -Are going to fail Intentionally","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [kuku] but found [Accounts Overview]","trace":"java.lang.AssertionError: expected [kuku] but found [Accounts Overview]\r\n\tat org.testng.Assert.fail(Assert.java:97)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:136)\r\n\tat org.testng.Assert.assertEquals(Assert.java:118)\r\n\tat org.testng.Assert.assertEquals(Assert.java:575)\r\n\tat org.testng.Assert.assertEquals(Assert.java:585)\r\n\tat extensions.Verifications.VerificationTextInElement(Verifications.java:19)\r\n\tat sanity.ParabankWeb.test01_verifyHeader(ParabankWeb.java:23)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(ArrayList.java:1257)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:770)\r\n\tat org.testng.TestRunner.run(TestRunner.java:591)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:402)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\n"},"stage":"finished","description":"This Test Verifies the Header :Accounts Overview After We log withDB Credentials - its going to be AssertionError to Give documentation for the report system for the screenshot and for the video recording. The AssertionError : Expected :kuku, Actual:Accounts Overview","steps":[],"attachments":[],"parameters":[{"name":"PlatformName","value":"web"}],"start":1634463198828,"stop":1634463199101,"uuid":"4f2c0a08-cb6b-4800-9ee9-b9d909ff1b92","historyId":"95703fe288c51b774931b0250b0bba60","fullName":"sanity.ParabankWeb.test01_verifyHeader","labels":[{"name":"package","value":"sanity.ParabankWeb"},{"name":"testClass","value":"sanity.ParabankWeb"},{"name":"testMethod","value":"test01_verifyHeader"},{"name":"parentSuite","value":"Web Suite"},{"name":"suite","value":"Web Tests"},{"name":"subSuite","value":"sanity.ParabankWeb"},{"name":"host","value":"DESKTOP-44HBIQT"},{"name":"thread","value":"12308@DESKTOP-44HBIQT.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}